version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/orbitronic
      - SECRET_KEY=your-secret-key
      - FLASK_APP=app.py  # Adjust if the Flask instance name is different (e.g., FLASK_APP=app:application)
      - FLASK_ENV=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["./wait-for-db.sh"]
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=orbitronic
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db-data:
